lerobot-train \
  --dataset.repo_id="slochmann/50_fold" \
  --policy.type="act" \
  --policy.repo_id="slochmann/act_fold" \
  --output_dir=outputs/train/act_fold_$(date +%Y%m%d_%H%M%S) \
  --job_name=act_fold \
  --policy.device=cuda \
  --wandb.enable=true \
  --wandb.project=derRoboter \
  --batch_size=8 \
  --steps=10000 \
  --policy.use_amp=true \
  --num_workers=8 \
  --policy.push_to_hub=true \
  --policy.private=true
